AMQP:
  HOST: "localhost"
  PORT: "5672"
  USER: "guest"
  PASSWORD: "guest"

  DRIVER: "amqp"
  URLTEMPLATE: "://%s:%s@%s:%s/"

DB:
  REDIS:
    HOST: "localhost"
    PORT: "6379"
    PASSWORD: "pass"
    USERNAME: "redis"

  PSQL:
    HOST: "localhost"
    PORT: "33061"
    USER: "postgres"
    PASSWORD: "pass"
    DBNAME: "userdb"

    DRIVER: "postgres"
    URLTEMPLATE: "host=%s port=%s dbname=%s notification=%s password=%s sslmode=disable"